[build-system]
requires = ["setuptools>42", "wheel"]
build-backend = "setuptools.build_meta"
packages = ["pkg2_data"]
package-dir = ["src"]
include-package-data = true

[project]
name = "pkg2_data"
version = "0.0.1"
