[build-system]
requires = ["setuptools>42"]
build-backend = "setuptools.build_meta"
packages = ["pkg1"]
package-dir = ["src"]
include-package-data = true

[project]
name = "pkg1"
version = "0.0.1"
dependencies = ["numpy", "tifffile"]
